Fundamentals of Deep Learning Models

# Lab 03-1: Multiclass Logistic Regression
## Exercise: Predicting Iris species using multinomial classification

This exercise implements **multinomial (multiclass) logistic regression** (Section 3.4) using the softmax activation function (Eq. 3.13) and cross-entropy loss (Eq. 3.16), trained via gradient descent with the simplified gradient $\partial J / \partial \mathbf{z} = \hat{\mathbf{y}} - \mathbf{y}$ (Eq. 3.32).
The model predicts iris species (setosa, versicolor, virginica) from four input features.

### Prepare Iris dataset

The Iris dataset (from scikit-learn) contains $N = 150$ samples with $M = 4$ continuous input features (sepal length, sepal width, petal length, petal width) and $K = 3$ class labels. The input matrix is $\mathbf{X} \in \mathbb{R}^{N \times M}$ and the target vector $\mathbf{y} \in \{0, 1, 2\}^N$.

In [1]:
import numpy as np
import pandas as pd

from sklearn import __version__ as sklearn_version

print('NumPy version:', np.__version__)
print('Pandas version:', pd.__version__)
print('scikit-learn version:', sklearn_version)

NumPy version: 2.0.2
Pandas version: 2.2.2
scikit-learn version: 1.6.1


In [2]:
from sklearn.datasets import load_iris

iris = load_iris()

# iris.data: four features (sepal length/width, petal length/width)
# iris.target: species labels (0=setosa, 1=versicolor, 2=virginica)
iris_df = pd.DataFrame(data= iris.data, columns= iris.feature_names)
iris_tf = pd.DataFrame(data= iris.target, columns= ['species'])

vX = iris_df.copy()
vY = iris_tf['species']

# Change dataset from pandas to numpy
vX = vX.to_numpy()
vY = vY.to_numpy()

### Presenting dataset samples

In [3]:
iris_df = pd.concat([iris_df, iris_tf], axis= 1)
iris_df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000


In [4]:
print(vY)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


### Splitting data for training and testing

The dataset is split into training and test sets (80/20). The integer class labels $y \in \{0,1,2\}$ are converted to one-hot encoded vectors $\mathbf{y} \in \{0,1\}^K$ for use with the cross-entropy loss (Eq. 3.16).

In [5]:
from sklearn.model_selection import train_test_split

# Split dataset into 80% train and 20% test
X_train, X_test, y_train_num, y_test = train_test_split(vX, vY, test_size= 0.20, random_state= 101)

# Convert integer labels to one-hot encoding for cross-entropy loss
n_train = y_train_num.shape[0]
y_train = np.zeros((n_train, 3))
for i in range(n_train):
    y_train[i, y_train_num[i]] = 1

### Multinomial logistic regression model

The model applies the softmax function (Eq. 3.13) after a linear transformation to produce class probabilities:

$$ \hat{\mathbf{y}}^{(i)} = \text{softmax}(\mathbf{W}\mathbf{x}^{(i)} + \mathbf{b}) $$

The cross-entropy cost function (Eq. 3.16) over $N$ training samples with $K$ classes is:

$$ J = -\frac{1}{N} \sum_{i=1}^{N} \sum_{k=1}^{K} y_k^{(i)} \log \hat{y}_k^{(i)} $$

Since the gradient of the softmax–cross-entropy combination simplifies to $\hat{\mathbf{y}} - \mathbf{y}$ (Eq. 3.32), the parameter gradients are:

$$ \frac{\partial J}{\partial \mathbf{W}} = \frac{1}{N} \sum_{i=1}^{N} (\hat{\mathbf{y}}^{(i)} - \mathbf{y}^{(i)}) \cdot (\mathbf{x}^{(i)})^T, \qquad \frac{\partial J}{\partial \mathbf{b}} = \frac{1}{N} \sum_{i=1}^{N} (\hat{\mathbf{y}}^{(i)} - \mathbf{y}^{(i)}) $$

Note: This notebook implements batch gradient descent over the full training set, rather than the per-sample SGD formulation.

#### Softmax function

The softmax function (Eq. 3.13) is defined as:

$$ \text{softmax}(z_i) = \frac{e^{z_i}}{\sum_{k=1}^{K} e^{z_k}} $$

For numerical stability, the maximum value is subtracted before exponentiation: $e^{z_i - \max(\mathbf{z})}$. This avoids overflow while preserving the output, since a common factor cancels in numerator and denominator.
Complete the code **without using `if` statement**.

In [ ]:
# Numerically stable softmax (Eq. 3.13)
def mySoftmax(x):

    ### START CODE HERE ###

    # Subtract max for numerical stability (does not change softmax output)
    x = None
    # Compute exponentials: e^{z_i}
    x = None
    # Normalize by sum of exponentials (Eq. 3.13)
    x = None

    ### END CODE HERE ###

    return x

In [7]:
# Verify numerical stability with extreme values
mySoftmax(np.array([0.0, 1000.0, -1000.0]))

array([0., 1., 0.])

#### Define model class

The model stores the weight matrix $\mathbf{W} \in \mathbb{R}^{K \times M}$ and bias vector $\mathbf{b} \in \mathbb{R}^{K}$, initialized to zeros.

In [8]:
class myLinearRegression:
    def __init__(self, n_out, n_in):
        self.weight = np.zeros((n_out, n_in))
        self.bias = np.zeros((n_out))

#### Create a model and check the matrix dimensions

$\mathbf{W}$: $(K \times M) = (3 \times 4)$, $\mathbf{b}$: $(K,) = (3,)$, $\mathbf{X}_{\text{train}}$: $(N \times M) = (120 \times 4)$, $\mathbf{y}_{\text{train}}$: $(N \times K) = (120 \times 3)$.

In [9]:
n_classes = 3
n_inputs  = 4

m = myLinearRegression(n_classes, n_inputs)

print(m.weight.shape, m.bias.shape)
print(X_train.shape, y_train.shape)

(3, 4) (3,)
(120, 4) (120, 3)


#### Training multinomial logistic regression

The training loop implements batch gradient descent. At each epoch:
1. Compute linear output: $\mathbf{z} = \mathbf{W}\mathbf{x} + \mathbf{b}$
2. Apply softmax: $\hat{\mathbf{y}} = \text{softmax}(\mathbf{z})$ (Eq. 3.13)
3. Compute gradients using $\hat{\mathbf{y}} - \mathbf{y}$ (Eq. 3.32)
4. Update parameters via gradient descent

In [ ]:
# Hyperparameters
alpha = 0.01
n_epochs = 1000

for epoch in range(n_epochs):

    ### START CODE HERE ###

    # Compute linear combination: z = W * X^T + b  (Eq. 3.13, input to softmax)
    y_lin  = None
    # Apply softmax to get predicted probabilities: y_hat = softmax(z)  (Eq. 3.13)
    y_prob = None

    # Compute prediction error: (y_hat - y)  (Eq. 3.32)
    y_diff = None
    # Update weights: W <- W - alpha * (1/N) * (y_hat - y)^T * X
    m.weight = None
    # Update bias: b <- b - alpha * mean(y_hat - y)
    m.bias = None

    # Compute cross-entropy loss (Eq. 3.16)
    loss_J = None

    ### END CODE HERE ###

    if ((epoch)%100==0):
        print('Epoch: %4d,  loss: %10.8f' % (epoch, loss_J))

print('Epoch: %4d,  loss: %10.8f' % (epoch, loss_J))

Epoch:    0,  loss: 1.09861229
Epoch:  100,  loss: 0.69879613
Epoch:  200,  loss: 0.57387569
Epoch:  300,  loss: 0.51143080
Epoch:  400,  loss: 0.47146165
Epoch:  500,  loss: 0.44214918
Epoch:  600,  loss: 0.41886941
Epoch:  700,  loss: 0.39944459
Epoch:  800,  loss: 0.38270677
Epoch:  900,  loss: 0.36796594
Epoch:  999,  loss: 0.35490760


In [11]:
# Verify trained parameters against expected values
res = np.concatenate((m.bias.reshape(-1,1), m.weight), axis=1)
exp = [[ 0.16648824,  0.31572872,  0.82871695, -1.18084542, -0.55357644],
       [ 0.08507611,  0.17324923, -0.27992939,  0.19214241, -0.18895642],
       [-0.25156435, -0.48897795, -0.54878756,  0.98870301,  0.74253287]]
if np.allclose(res,exp): print('test passed.')
else: print('test failed.')

test passed.


### Evaluate model performance

The trained model is evaluated on the test set by computing predictions via forward propagation and comparing them against the ground-truth labels using accuracy.

In [ ]:
from sklearn.metrics import accuracy_score

def my_predict(m, X_test):

    ### START CODE HERE ###

    # Forward pass: compute linear output z = W * X^T + b
    y_lin  = None
    # Apply softmax to obtain class probabilities (Eq. 3.13)
    y_prod = None
    # Select class with highest probability (Eq. 3.4)
    y_pred = None

    ### END CODE HERE ###

    return y_pred

y_pred = my_predict(m, X_test)

print(y_test)
print(y_pred)

accuracy_score(y_pred, y_test)

[0 0 0 2 1 2 1 1 2 0 2 0 0 2 2 1 1 1 0 2 1 0 1 1 1 1 1 2 0 0]
[0 0 0 2 1 2 1 1 2 0 2 0 0 2 2 1 1 1 0 2 1 0 1 1 1 1 1 2 0 0]


1.0

In [13]:
# Verify that predictions match ground truth on test set
if np.allclose(y_pred, y_test): print('test passed.')
else: print('test failed.')

test passed.


### Comparison with scikit-learn LogisticRegression

scikit-learn's `LogisticRegression` uses a regularized multinomial logistic regression solved via L-BFGS (a quasi-Newton method), which differs from the unregularized batch gradient descent used above.

In [14]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

# Training the model
lr.fit(X_train, y_train_num)

# Making predictions
s_pred = lr.predict(X_test)

accuracy_score(s_pred, y_test)

1.0

### Test model with a random sample

In [15]:
idx = np.random.randint(X_test.shape[0])
test_in = np.expand_dims(X_test[idx], axis=0)

species = ['setosa', 'versicolor', 'virginica']

y_pred = my_predict(m, test_in)
s_pred = lr.predict(test_in)

print('My Prediction for Iris Species:', species[y_pred[0]])
print('SK Prediction for Iris Species:', species[s_pred[0]])
print('True Iris Species is:', species[y_test[idx]])

My Prediction for Iris Species: setosa
SK Prediction for Iris Species: setosa
True Iris Species is: setosa


(c) 2026 S. W. Lee